/*
 * port_quicksave.c — multi-slot save-states with disk persistence + auto-save.
 *
 * Snapshots a curated set of game-state regions into an in-memory slot
 * on save, restores them on load. Slots also get serialized to disk as
 * `state_<slot>.bin` next to the binary so they survive restart.
 *
 * Slot layout:
 *   slot 0:    F5 quicksave / F6 quickload (legacy single-slot API)
 *   slot 1-4:  F1..F4 load,  Shift+F1..F4 save (numbered manual slots)
 *   slot 5-7:  auto-save ring (Port_QuickSave_Auto cycles through these)
 *
 * File format (disk persistence):
 *   magic    "TMCS"                          (4 bytes)
 *   version  PORT_QUICKSAVE_VERSION          (u32 LE)
 *   total    sum of all region sizes         (u32 LE)
 *   saved_at timestamp                       (u64 LE)
 *   region   ROM region tag                  (u32 LE)
 *   layout   build layout signature          (u64 LE)
 *   image    program image start, end        (2 x u64 LE)
 *   portable every code/constant pointer named (u32 LE)
 *   regions  directory: name, size, address  (u32 count + entries)
 *   pointers ROM/heap/symbol pointer records (u32 count + records)
 *   data     concatenated region bytes       (in directory order)
 *
 * On load, if magic/version don't match, the file is rejected silently; a
 * different ROM region, or another build when the state isn't portable
 * (or tmc_pc.syms is missing), or a shared region that changed size, is
 * refused with a log line — the in-memory snapshot (if any) stays
 * untouched. This is
 * defensive against schema changes between builds; saves are best-effort,
 * not a contract.
 *
 * Coverage: emulated GBA memory (EWRAM/IWRAM/VRAM/IO), the save file,
 * the player + state, the room controls + transition, gMain, and the
 * entity pools, list heads, allocation counts and active item state.
 * This is not a complete serialization of every host global or heap asset;
 * HUD, OAM, graphics allocation and script/asset state are not fully covered.
 *
 * Caveats:
 *  - Snapshotting mid-frame is supported but the visible result is
 *    "next frame" — entity logic that ran this frame may have already
 *    written to OAM, which is not snapshotted.
 *  - Save-states are not the same as the game's in-engine save file
 *    (`tmc.sav`). The game's own save still goes through its file-select
 *    flow. Save-states capture transient runtime state including
 *    mid-cutscene positions.
 */

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <time.h>

#include <SDL3/SDL.h>

#include "structures.h"
#include "save.h"
#include "main.h"
#include "entity.h"
#include "port_gba_mem.h"
#include "port_runtime_config.h"
#include "region.h" /* REGION_IS_EU/JP — per-region savestate isolation (#21) */
#include "hitbox.h"
#include "port_asset_loader.h"
#include "port_rom.h"
/* types of the generated RAM regions (port_quicksave_regions.h) */
#include "affine.h"
#include "area.h"
#include "backgroundAnimations.h"
#include "beanstalkSubtask.h"
#include "collision.h"
#include "color.h"
#include "fade.h"
#include "kinstone.h"
#include "manager/diggingCaveEntranceManager.h"
#include "map.h"
#include "message.h"
#include "npc.h"
#include "pauseMenu.h"
#include "player.h"
#include "room.h"
#include "screen.h"
#include "script.h"
#include "scroll.h"
#include "port_voxel.h"
#include "port_ptr_registry.h"
#include "port_syms.h"
extern int Port_CaptureBaseFramebufferPNG(const char* path);

extern u8 gEwram[];
extern u8 gIwram[];
extern u8 gVram[];
extern u8 gIoMem[];
extern LinkedList gEntityListsBackup[9];
extern Entity* gPlayerClones[3];
extern UpdateContext gUpdateContext;

/* The gameplay PRNG seed. On GBA this lived in IWRAM (0x03001150) and was
 * therefore captured by an IWRAM-snapshotting savestate; in the port it is a
 * standalone host global (port_linked_stubs.c), so it must be listed explicitly
 * or QuickLoad would restore everything EXCEPT RNG state and desync manips. */
extern u32 gRand;

/* Speedrun-practice IGT frame counter (port_practice.c). Listed as a region
 * so loading any savestate rewinds the practice timer to the value captured
 * with that state — "reload the section and the timer comes back too". */
extern u64 gPracticeFrame;

/* Defined in src/player.c — re-resolves the player's .rodata hitbox pointer
   from the current form after a cross-process quickload. Static asset data
   lies outside the captured regions and cannot use their relocation table. */
void Port_RestorePlayerHitbox(void);

/* Every other game RAM variable (linker.ld) the port defines as a host
 * global: the room's maps and collision, area, room vars, scripts, managers,
 * HUD, message box... Generated by tools/gen_quicksave_regions.py. */
#define QS_DECL(decl) decl
#define QS_REGION(name, ptrs)
#define QS_PRIVATE(name, ptrs)
#include "port_quicksave_regions.h"
#undef QS_DECL
#undef QS_REGION
#undef QS_PRIVATE

typedef struct {
    void* ptr;
    size_t size;
    const char* name;
    int hasPointers;
    const unsigned* privateSize; /* type private to its .c file: size exported there */
} StateRegion;

/* List of regions captured by a save-state. The order doesn't matter for
 * save, but for restore the order must stay consistent with what was on
 * disk — which is why the disk format records the total size and we
 * reject files that don't match the current region layout. */
static StateRegion sRegions[] = {
    { gEwram, 0x40000, "gEwram" },
    { gIwram, 0x8000, "gIwram" },
    { gVram, 0x18000, "gVram" },
    { gIoMem, 0x400, "gIoMem" },
    /* palette RAM and OAM: without them a state loaded into another room or
     * a fresh process shows the old palettes (a black screen from the title) */
    { gBgPltt, sizeof(gBgPltt), "gBgPltt" },
    { gObjPltt, sizeof(gObjPltt), "gObjPltt" },
    { gOamMem, sizeof(gOamMem), "gOamMem" },
    { &gSave, sizeof(gSave), "gSave" },
    { &gPlayerEntity, sizeof(gPlayerEntity), "gPlayerEntity", 1 },
    { &gPlayerState, sizeof(gPlayerState), "gPlayerState", 1 },
    { &gMain, sizeof(gMain), "gMain" },
    { &gRoomControls, sizeof(gRoomControls), "gRoomControls", 1 },
    { &gRoomTransition, sizeof(gRoomTransition), "gRoomTransition", 1 },
    { gEntities, sizeof(gEntities), "gEntities", 1 },
    { &gRand, sizeof(gRand), "gRand" },
    { &gPracticeFrame, sizeof(gPracticeFrame), "gPracticeFrame" },
    { gEntityLists, sizeof(gEntityLists), "gEntityLists", 1 },
    { gEntityListsBackup, sizeof(gEntityListsBackup), "gEntityListsBackup", 1 },
    { gAuxPlayerEntities, sizeof(gAuxPlayerEntities), "gAuxPlayerEntities", 1 },
    { &gCarriedEntity, sizeof(gCarriedEntity), "gCarriedEntity", 1 },
    { &gEntCount, sizeof(gEntCount), "gEntCount" },
    { &gManagerCount, sizeof(gManagerCount), "gManagerCount" },
    { gActiveItems, sizeof(gActiveItems), "gActiveItems", 1 },
    { gPlayerClones, sizeof(gPlayerClones), "gPlayerClones", 1 },
    { &gUpdateContext, sizeof(gUpdateContext), "gUpdateContext", 1 },
#define QS_DECL(decl)
#define QS_REGION(name, ptrs) { &name, sizeof(name), #name, ptrs },
#define QS_PRIVATE(name, ptrs) { name, 0, #name, ptrs, &gQsSize_##name },
#include "port_quicksave_regions.h"
#undef QS_DECL
#undef QS_REGION
#undef QS_PRIVATE
};

#define NUM_REGIONS (sizeof(sRegions) / sizeof(sRegions[0]))
#define NUM_SLOTS 8 /* 0..4 manual + 5..7 auto-save ring */
#define AUTO_SLOT_BASE 5
#define NUM_AUTO_SLOTS 3
#define MAGIC 0x53434D54u /* "TMCS" little-endian */
#define VERSION                                         \
    11u /* v2: header carries gEntities base address for \
        * cross-process pointer-fixup on restore.       \
        * v3: gRand added to region list so RNG         \
        * state round-trips (GBA had it in IWRAM).      \
        * v4: gPracticeFrame added so speedrun IGT      \
        * timer rewinds with state.                     \
        * v5: ROM region tag — USA state restored     \
        * into a JP session contaminates tmc_jp.sav     \
        * (#21); cross-region loads are refused.        \
        * v6: entity subclass layouts changed; older    \
        * snapshots are rejected.                       \
        * v7: entity bookkeeping and per-region bases   \
        * for relocating both nodes and list sentinels. \
        * v7 is also the first with gSave.flags at the  \
        * retail 0x25C; v6 may hold the old PC layout.  \
        * v8: build layout signature + program image    \
        * range: states from another build are refused, \
        * same-build pointers into the image relocated. \
        * v9: every game RAM global (linker.ld), not    \
        * only the entity pools: maps, area, scripts... \
        * v10: pointer table: pointers into the ROM and \
        * named heap blocks, resolved again on load.    \
        * v11: regions by name, pointers into code and  \
        * constants by symbol (tmc_pc.syms): states     \
        * load in later builds. */

typedef struct {
    u8* snapshot; /* heap, NULL if slot empty */
    size_t bytes;
    int valid;
    u64 saved_at_unix;       /* clock_gettime CLOCK_REALTIME seconds */
    u64 saved_bases[NUM_REGIONS]; /* native addresses when captured */
    u64 image_lo, image_hi;       /* program image when captured (0 = unknown) */
    struct PtrRec* recs;          /* pointers into the ROM, named heap blocks, code */
    u32 nrecs;
    int portable;                 /* every pointer into code/constants has a symbol */
} Slot;

/* A pointer the region/image relocation can't fix: into the ROM buffer or a
 * named heap block (asset file, area table...; port_ptr_registry). Recorded by
 * what it points at, resolved again on restore, so it survives a new process
 * where those buffers sit elsewhere or aren't loaded yet. */
enum { PTR_ROM = 1, PTR_BLOCK = 2, PTR_SYMBOL = 3 };
typedef struct PtrRec {
    u16 region;     /* sRegions index holding the pointer */
    u8 kind;        /* PTR_ROM / PTR_BLOCK / PTR_SYMBOL */
    u8 keyLen;      /* PTR_BLOCK / PTR_SYMBOL: bytes of key */
    u32 at;         /* offset of the pointer in that region */
    u64 offset;     /* into the ROM / the block / the symbol */
    char key[112];  /* PTR_BLOCK: block name, PTR_SYMBOL: symbol name */
} PtrRec;

static Slot sSlots[NUM_SLOTS];
static int sAutoNextSlot = AUTO_SLOT_BASE; /* round-robin cursor */
static u64 sAutoLastSaveTicksMs = 0;
static int sAutoEnabled = 1;        /* on by default — the F8
                                       toggle (and config.json)
                                       can flip it off. */
static u32 sAutoIntervalMs = 60000; /* 60 seconds default */

/* Area-change auto-save (independent of the interval timer). Tracks
 * the last-observed (area, room) and saves to the ring whenever it
 * changes. Helps with the crash-on-load-then-lose-an-hour case Jester
 * flagged. */
static int sAutoOnAreaChange = 1;
static u8 sLastSeenArea = 0xFF;
static u8 sLastSeenRoom = 0xFF;

/* The program image: code, constants and statics. Entities point into it
 * (hitboxes, scripts, animation tables) and it moves as a whole when the OS
 * loads the program somewhere else (ASLR, e.g. after a reboot), so a state
 * from an earlier process relocates those pointers by the image's shift. */
#if defined(_WIN32)
extern char __ImageBase[];
static void ImageRange(u64* lo, u64* hi) {
    /* PE: e_lfanew at 0x3C; SizeOfImage 56 bytes into the optional header,
     * which follows the 4-byte signature and the 20-byte file header. */
    u32 peOffset, sizeOfImage;
    memcpy(&peOffset, __ImageBase + 0x3C, sizeof(peOffset));
    memcpy(&sizeOfImage, __ImageBase + peOffset + 4 + 20 + 56, sizeof(sizeOfImage));
    *lo = (u64)(uintptr_t)__ImageBase;
    *hi = *lo + sizeOfImage;
}
#elif defined(__linux__) && !defined(__ANDROID__)
extern char __executable_start[], _end[];
static void ImageRange(u64* lo, u64* hi) {
    *lo = (u64)(uintptr_t)__executable_start;
    *hi = (u64)(uintptr_t)_end;
}
#else
static void ImageRange(u64* lo, u64* hi) {
    *lo = *hi = 0; /* unknown: no image relocation */
}
#endif

/* Differs between builds whose code or data moved relative to each other:
 * a state holds raw pointers into that layout, so only the build that wrote
 * it can read it back. */
static u64 LayoutSignature(void) {
    u64 lo, hi;
    ImageRange(&lo, &hi);
    const uintptr_t base = (uintptr_t)gEwram;
    return ((u64)((uintptr_t)&gPlayerHitbox - base) * 1000003u) ^
           ((u64)((uintptr_t)&LayoutSignature - base) << 20) ^ (hi - lo);
}

static size_t TotalRegionBytes(void) {
    for (size_t i = 0; i < NUM_REGIONS; i++)
        if (sRegions[i].privateSize)
            sRegions[i].size = *sRegions[i].privateSize;
    size_t total = 0;
    for (size_t i = 0; i < NUM_REGIONS; i++) {
        total += sRegions[i].size;
    }
    return total;
}

static int InCapturedRegion(uintptr_t v) {
    for (size_t t = 0; t < NUM_REGIONS; ++t)
        if (v >= (uintptr_t)sRegions[t].ptr && v - (uintptr_t)sRegions[t].ptr < sRegions[t].size)
            return 1;
    return 0;
}

/* Every pointer-sized word of the pointer-bearing regions that points into the
 * ROM buffer or a named heap block, as a PtrRec. Words pointing into captured
 * regions or the program image are left to FixupEntityPointers. */
static void RecordHeapPointers(Slot* s) {
    u32 n = 0, cap = s->nrecs;
    u64 imageLo, imageHi;
    ImageRange(&imageLo, &imageHi);
    const int syms = Port_Syms_Available();
    s->portable = syms;
    for (size_t i = 0; i < NUM_REGIONS; ++i) {
        if (!sRegions[i].hasPointers)
            continue;
        const u8* bytes = sRegions[i].ptr;
        for (size_t off = 0; off + sizeof(uintptr_t) <= sRegions[i].size; off += sizeof(uintptr_t)) {
            uintptr_t v;
            memcpy(&v, bytes + off, sizeof(v));
            if (v < 0x10000 || InCapturedRegion(v))
                continue;
            PtrRec r;
            memset(&r, 0, sizeof(r));
            const char* key;
            size_t boff;
            if (v >= imageLo && v < imageHi) {
                /* code or constants: by symbol, so another build can find it */
                u64 soff;
                const size_t len = syms && Port_Syms_Lookup((const void*)v, &key, &soff) ? strlen(key) : 0;
                if (len == 0 || len >= sizeof(r.key)) {
                    s->portable = 0;
                    continue;
                }
                r.kind = PTR_SYMBOL, r.offset = soff, r.keyLen = (u8)len;
                memcpy(r.key, key, len);
            } else if (gRomData && v >= (uintptr_t)gRomData && v - (uintptr_t)gRomData < gRomSize) {
                r.kind = PTR_ROM, r.offset = v - (uintptr_t)gRomData;
            } else if (Port_PtrBlock_Lookup((const void*)v, &key, &boff)) {
                const size_t len = strlen(key);
                if (len >= sizeof(r.key))
                    continue;
                r.kind = PTR_BLOCK, r.offset = boff, r.keyLen = (u8)len;
                memcpy(r.key, key, len);
            } else {
                continue;
            }
            r.region = (u16)i, r.at = (u32)off;
            if (n == cap) {
                cap = cap ? cap * 2 : 64;
                PtrRec* grown = (PtrRec*)realloc(s->recs, cap * sizeof(PtrRec));
                if (!grown)
                    break;
                s->recs = grown;
            }
            s->recs[n++] = r;
        }
    }
    s->nrecs = n;
}

/* Points every recorded word at its target in this process. A target that
 * can't be resolved (asset missing) becomes NULL rather than a stale address. */
static void ResolveHeapPointers(const Slot* s) {
    u32 lost = 0;
    for (u32 k = 0; k < s->nrecs; ++k) {
        const PtrRec* r = &s->recs[k];
        if (r->region >= NUM_REGIONS || r->at + sizeof(uintptr_t) > sRegions[r->region].size)
            continue;
        void* p = NULL;
        if (r->kind == PTR_ROM) {
            p = gRomData && r->offset < gRomSize ? gRomData + r->offset : NULL;
        } else {
            char key[sizeof(r->key) + 1];
            memcpy(key, r->key, r->keyLen);
            key[r->keyLen] = 0;
            if (r->kind == PTR_BLOCK) {
                p = Port_PtrBlock_Resolve(key, (size_t)r->offset);
            } else if (r->kind == PTR_SYMBOL) {
                u8* sym = (u8*)Port_Syms_Resolve(key);
                p = sym ? sym + r->offset : NULL;
            }
        }
        lost += p == NULL;
        const uintptr_t v = (uintptr_t)p;
        memcpy((u8*)sRegions[r->region].ptr + r->at, &v, sizeof(v));
    }
    if (lost)
        fprintf(stderr, "[quicksave] %u of %u heap pointers could not be resolved (set to NULL)\n", lost, s->nrecs);
}

static int Snapshot_Capture(Slot* s) {
    const size_t total = TotalRegionBytes();
    if (s->snapshot == NULL || s->bytes != total) {
        free(s->snapshot);
        s->snapshot = (u8*)malloc(total);
        if (s->snapshot == NULL) {
            s->bytes = 0;
            s->valid = 0;
            fprintf(stderr, "[quicksave] alloc failed (%zu bytes)\n", total);
            return 0;
        }
        s->bytes = total;
    }
    u8* dst = s->snapshot;
    for (size_t i = 0; i < NUM_REGIONS; i++) {
        memcpy(dst, sRegions[i].ptr, sRegions[i].size);
        dst += sRegions[i].size;
        s->saved_bases[i] = (u64)(uintptr_t)sRegions[i].ptr;
    }
    ImageRange(&s->image_lo, &s->image_hi);
    RecordHeapPointers(s);
    s->valid = 1;
    s->saved_at_unix = (u64)time(NULL);
    {
        /* ponytail: debug knob — TMC_QS_POINTER_REPORT=<file>: classify every
         * pointer-sized word of the pointer-bearing regions by what it points
         * into (a captured region, the program image, the ROM buffer, a loaded
         * asset, other heap), for making states portable across builds. */
        const char* rp = getenv("TMC_QS_POINTER_REPORT");
        FILE* f = rp && *rp ? fopen(rp, "w") : NULL;
        if (f) {
            unsigned counts[5] = { 0 };
            static const char* kKinds[5] = { "region", "image", "rom", "asset", "heap?" };
            for (size_t i = 0; i < NUM_REGIONS; ++i) {
                if (!sRegions[i].hasPointers)
                    continue;
                const u8* bytes = sRegions[i].ptr;
                for (size_t off = 0; off + sizeof(uintptr_t) <= sRegions[i].size; off += sizeof(uintptr_t)) {
                    uintptr_t v;
                    memcpy(&v, bytes + off, sizeof(v));
                    if (v < 0x10000)
                        continue;
                    int kind = -1;
                    size_t t = 0;
                    for (; t < NUM_REGIONS; ++t)
                        if (v >= (uintptr_t)sRegions[t].ptr && v - (uintptr_t)sRegions[t].ptr < sRegions[t].size) {
                            kind = 0;
                            break;
                        }
                    if (kind < 0 && v >= s->image_lo && v < s->image_hi)
                        kind = 1;
                    else if (kind < 0 && gRomData && v >= (uintptr_t)gRomData && v - (uintptr_t)gRomData < gRomSize)
                        kind = 2;
                    else if (kind < 0 && Port_IsLoadedAssetBytes((const void*)v, 1))
                        kind = 3;
                    else if (kind < 0 && (v >> 32) != 0 && (v >> 48) == 0)
                        kind = 4;
                    if (kind < 0)
                        continue;
                    counts[kind]++;
                    if (kind == 0)
                        fprintf(f, "region %s+0x%zx -> %s+0x%zx\n", sRegions[i].name, off, sRegions[t].name,
                                (size_t)(v - (uintptr_t)sRegions[t].ptr));
                    else if (kind == 1)
                        fprintf(f, "image  %s+0x%zx -> rva 0x%llx\n", sRegions[i].name, off,
                                (unsigned long long)(v - s->image_lo));
                    else if (kind == 2)
                        fprintf(f, "rom    %s+0x%zx -> rom+0x%llx\n", sRegions[i].name, off,
                                (unsigned long long)(v - (uintptr_t)gRomData));
                    else
                        fprintf(f, "%-6s %s+0x%zx -> %p\n", kKinds[kind], sRegions[i].name, off, (void*)v);
                }
            }
            fprintf(f, "summary region=%u image=%u rom=%u asset=%u heap?=%u\n", counts[0], counts[1], counts[2],
                    counts[3], counts[4]);
            fclose(f);
        }
    }
    return 1;
}

static int Snapshot_MatchesCurrent(const Slot* s, const char** region, size_t* offset, u8* expected, u8* actual) {
    const u8* src;
    size_t i;

    if (!s->valid || s->snapshot == NULL || s->bytes != TotalRegionBytes()) {
        *region = "snapshot";
        *offset = 0;
        *expected = 0;
        *actual = 0;
        return 0;
    }

    src = s->snapshot;
    for (i = 0; i < NUM_REGIONS; i++) {
        const u8* current = (const u8*)sRegions[i].ptr;
        size_t j;

        if (memcmp(src, current, sRegions[i].size) == 0) {
            src += sRegions[i].size;
            continue;
        }
        for (j = 0; j < sRegions[i].size && src[j] == current[j]; j++) {}
        *region = sRegions[i].name;
        *offset = j;
        *expected = src[j];
        *actual = current[j];
        return 0;
    }
    return 1;
}

/* Relocate references between captured native regions, including list heads,
 * sentinels, the player and auxiliary entities. As in the old entity-only
 * fixup, aligned words in pointer-bearing structs are matched by address
 * range; raw emulated memory and integer-only globals are never scanned.
 * This does not serialize arbitrary heap allocations or asset pointers. */
static void FixupEntityPointers(const Slot* s) {
    u64 imageLo, imageHi;
    ImageRange(&imageLo, &imageHi);
    const int moveImage = s->image_lo != 0 && imageLo != 0 && s->image_lo != imageLo;
    for (size_t i = 0; i < NUM_REGIONS; ++i) {
        if (!sRegions[i].hasPointers)
            continue;
        u8* bytes = sRegions[i].ptr;
        for (size_t offset = 0; offset + sizeof(uintptr_t) <= sRegions[i].size; offset += sizeof(uintptr_t)) {
            uintptr_t value;
            memcpy(&value, bytes + offset, sizeof(value));
            for (size_t target = 0; target < NUM_REGIONS; ++target) {
                u64 base = s->saved_bases[target];
                if (base != 0 && value >= base && value - base < sRegions[target].size) {
                    value = (uintptr_t)sRegions[target].ptr + (uintptr_t)(value - base);
                    memcpy(bytes + offset, &value, sizeof(value));
                    break;
                }
                if (target + 1 == NUM_REGIONS && moveImage && value >= s->image_lo && value < s->image_hi) {
                    value = (uintptr_t)(imageLo + (value - s->image_lo));
                    memcpy(bytes + offset, &value, sizeof(value));
                }
            }
        }
    }
}

static int Snapshot_Restore(const Slot* s) {
    if (!s->valid || s->snapshot == NULL || s->bytes != TotalRegionBytes()) {
        return 0;
    }
    const u8* src = s->snapshot;
    for (size_t i = 0; i < NUM_REGIONS; i++) {
        memcpy(sRegions[i].ptr, src, sRegions[i].size);
        src += sRegions[i].size;
    }
    /* Same-process snapshots already carry current addresses. */
    if (s->saved_bases[0] != (u64)(uintptr_t)sRegions[0].ptr) {
        FixupEntityPointers(s);
        /* The player's hitbox is static asset data outside the snapshot.
         * Preserve relocated entity camera targets; replace unknown targets. */
        uintptr_t ct = (uintptr_t)gRoomControls.camera_target;
        uintptr_t lo = (uintptr_t)gEntities;
        uintptr_t hi = lo + sizeof(gEntities);
        if (ct == 0 || ct < lo || ct >= hi) {
            gRoomControls.camera_target = (Entity*)&gPlayerEntity;
        }
        Port_RestorePlayerHitbox();
    }
    /* Heap and ROM targets move between processes even when the image and
     * regions don't; resolving them is a no-op within one process. */
    ResolveHeapPointers(s);
    return 1;
}

/* Headless deterministic restore/replay gate. With no external input, advance
 * the same 120 engine frames twice from one snapshot and require every saved
 * byte to agree. Runs here so capture/restore stays on a frame boundary. */
static int QuickSaveReplayTestTick(void) {
    enum {
        SETTLE_FRAMES = 30,
        DEFAULT_REPLAY_FRAMES = 120,
        MAX_REPLAY_FRAMES = 3600,
    };
    static int enabled = -1;
    static int phase = 0;
    static unsigned int phaseFrame = 0;
    static unsigned int replayFrames = DEFAULT_REPLAY_FRAMES;
    static Slot start;
    static Slot expectedEnd;
    const char* region;
    size_t offset;
    u8 expected;
    u8 actual;

    if (enabled < 0) {
        const char* env = getenv("TMC_REPRO_QUICKSAVE_ROUNDTRIP");
        enabled = env != NULL && env[0] != '\0' && strcmp(env, "0") != 0;
        if (enabled) {
            const char* frames = getenv("TMC_REPRO_QUICKSAVE_FRAMES");
            char* end;
            unsigned long requested = frames != NULL ? strtoul(frames, &end, 10) : 0;
            if (frames != NULL && requested > 0 && requested <= MAX_REPLAY_FRAMES && end != frames && *end == '\0') {
                replayFrames = (unsigned int)requested;
            }
            fprintf(stderr, "[quicksave-test] enabled: settle=%d replay=%u frames\n", SETTLE_FRAMES, replayFrames);
        }
    }
    if (!enabled) {
        return 0;
    }

    if (phase == 0 && gMain.task != TASK_GAME) {
        phaseFrame = 0;
        return 1;
    }

    phaseFrame++;
    if (phase == 0 && phaseFrame >= SETTLE_FRAMES) {
        if (!Snapshot_Capture(&start)) {
            fprintf(stderr, "[quicksave-test] FAIL: initial capture failed\n");
            fflush(stderr);
            _Exit(1);
        }
        fprintf(stderr, "[quicksave-test] captured start (%zu bytes)\n", start.bytes);
        phase = 1;
        phaseFrame = 0;
    } else if (phase == 1 && phaseFrame >= replayFrames) {
        if (!Snapshot_Capture(&expectedEnd) || !Snapshot_Restore(&start)) {
            fprintf(stderr, "[quicksave-test] FAIL: endpoint capture or restore failed\n");
            fflush(stderr);
            _Exit(1);
        }
        if (!Snapshot_MatchesCurrent(&start, &region, &offset, &expected, &actual)) {
            fprintf(stderr, "[quicksave-test] FAIL: restore mismatch %s+0x%zx expected=%02x actual=%02x\n", region,
                    offset, (unsigned)expected, (unsigned)actual);
            fflush(stderr);
            _Exit(1);
        }
        fprintf(stderr, "[quicksave-test] restored start; replaying\n");
        phase = 2;
        phaseFrame = 0;
    } else if (phase == 2 && phaseFrame >= replayFrames) {
        if (!Snapshot_MatchesCurrent(&expectedEnd, &region, &offset, &expected, &actual)) {
            fprintf(stderr, "[quicksave-test] FAIL: replay mismatch %s+0x%zx expected=%02x actual=%02x\n", region,
                    offset, (unsigned)expected, (unsigned)actual);
            fflush(stderr);
            _Exit(1);
        }
        fprintf(stderr, "[quicksave-test] PASS: %u-frame replay byte-identical (%zu bytes)\n", replayFrames,
                expectedEnd.bytes);
        fflush(stderr);
        _Exit(0);
    }

    return 1;
}

/* Region tag for the state header + per-region state filenames. EU/JP get
 * their own state files (like tmc_eu.sav / tmc_jp.sav) so sessions never
 * even see another region's states; USA keeps the legacy names. */
static u32 ActiveRegionTag(void) {
    if (REGION_IS_EU)
        return 2;
    if (REGION_IS_JP)
        return 3;
    return 1; /* USA */
}

static void SlotFilename(int slot, char* out, size_t cap) {
    const char* prefix = REGION_IS_EU ? "state_eu" : REGION_IS_JP ? "state_jp" : "state";
    if (slot >= AUTO_SLOT_BASE) {
        snprintf(out, cap, "%s_auto_%d.bin", prefix, slot - AUTO_SLOT_BASE);
    } else if (slot == 0) {
        snprintf(out, cap, "%s_quick.bin", prefix);
    } else {
        snprintf(out, cap, "%s_%d.bin", prefix, slot);
    }
}

static int WriteSlotToDisk(int slot) {
    if (slot < 0 || slot >= NUM_SLOTS)
        return 0;
    Slot* s = &sSlots[slot];
    if (!s->valid || s->snapshot == NULL)
        return 0;

    char path[64];
    SlotFilename(slot, path, sizeof(path));
    FILE* f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "[quicksave] open %s for write failed\n", path);
        return 0;
    }
    const u32 magic = MAGIC;
    const u32 version = VERSION;
    const u32 total = (u32)s->bytes;
    const u64 saved_at = s->saved_at_unix;
    const u32 region_tag = ActiveRegionTag();
    const u64 layout = LayoutSignature();
    const u32 portable = (u32)s->portable;
    const u32 nregions = (u32)NUM_REGIONS;
    int ok = fwrite(&magic, sizeof(magic), 1, f) == 1 && fwrite(&version, sizeof(version), 1, f) == 1 &&
             fwrite(&total, sizeof(total), 1, f) == 1 && fwrite(&saved_at, sizeof(saved_at), 1, f) == 1 &&
             fwrite(&region_tag, sizeof(region_tag), 1, f) == 1 && fwrite(&layout, sizeof(layout), 1, f) == 1 &&
             fwrite(&s->image_lo, sizeof(s->image_lo), 1, f) == 1 &&
             fwrite(&s->image_hi, sizeof(s->image_hi), 1, f) == 1 && fwrite(&portable, sizeof(portable), 1, f) == 1 &&
             fwrite(&nregions, sizeof(nregions), 1, f) == 1;
    /* region directory: name, size and address, in data order */
    for (size_t i = 0; ok && i < NUM_REGIONS; ++i) {
        const u8 len = (u8)strlen(sRegions[i].name);
        const u32 size = (u32)sRegions[i].size;
        ok = fwrite(&len, 1, 1, f) == 1 && fwrite(sRegions[i].name, 1, len, f) == len &&
             fwrite(&size, sizeof(size), 1, f) == 1 && fwrite(&s->saved_bases[i], sizeof(u64), 1, f) == 1;
    }
    /* pointer records: count, then region u16, kind u8, keyLen u8, at u32,
     * offset u64, key bytes */
    ok = ok && fwrite(&s->nrecs, sizeof(s->nrecs), 1, f) == 1;
    for (u32 k = 0; ok && k < s->nrecs; ++k) {
        const PtrRec* r = &s->recs[k];
        ok = fwrite(&r->region, sizeof(r->region), 1, f) == 1 && fwrite(&r->kind, 1, 1, f) == 1 &&
             fwrite(&r->keyLen, 1, 1, f) == 1 && fwrite(&r->at, sizeof(r->at), 1, f) == 1 &&
             fwrite(&r->offset, sizeof(r->offset), 1, f) == 1 && fwrite(r->key, 1, r->keyLen, f) == r->keyLen;
    }
    ok = ok && fwrite(s->snapshot, 1, s->bytes, f) == s->bytes;
    fclose(f);
    if (!ok)
        fprintf(stderr, "[quicksave] write failed for %s\n", path);
    return ok;
}

/* Reads the fixed 4-field slot header (magic, version, total, saved_at).
 * Returns 1 if all four fields read, 0 on short read. Field values are
 * not validated and no diagnostics are emitted — callers decide. */
static int ReadSlotHeader(FILE* f, u32* magic, u32* version, u32* total, u64* saved_at) {
    return fread(magic, sizeof(*magic), 1, f) == 1 && fread(version, sizeof(*version), 1, f) == 1 &&
           fread(total, sizeof(*total), 1, f) == 1 && fread(saved_at, sizeof(*saved_at), 1, f) == 1;
}

/* Loads a slot file into sSlots[slot], laid out for this build: regions are
 * matched by name, so a state from another build loads as long as every
 * region it shares with this one kept its size and every pointer it holds
 * into code or constants was recorded by symbol. Regions this build added
 * keep their current contents. */
static int ReadSlotFromDisk(int slot) {
    if (slot < 0 || slot >= NUM_SLOTS)
        return 0;
    TotalRegionBytes(); /* fills in the private-type region sizes */
    char path[64];
    SlotFilename(slot, path, sizeof(path));
    FILE* f = fopen(path, "rb");
    if (!f)
        return 0;
    u32 magic = 0, version = 0, total = 0, region_tag = 0, portable = 0, nregions = 0;
    u64 saved_at = 0, layout = 0, image_lo = 0, image_hi = 0;
    if (!ReadSlotHeader(f, &magic, &version, &total, &saved_at) || magic != MAGIC || version != VERSION ||
        fread(&region_tag, sizeof(region_tag), 1, f) != 1 || fread(&layout, sizeof(layout), 1, f) != 1 ||
        fread(&image_lo, sizeof(image_lo), 1, f) != 1 || fread(&image_hi, sizeof(image_hi), 1, f) != 1 ||
        fread(&portable, sizeof(portable), 1, f) != 1 || fread(&nregions, sizeof(nregions), 1, f) != 1 ||
        nregions > 1024) {
        fclose(f);
        return 0;
    }
    if (region_tag != ActiveRegionTag()) {
        fprintf(stderr, "[quicksave] %s was saved in a different ROM region (%u != %u) — refusing load\n", path,
                region_tag, ActiveRegionTag());
        fclose(f);
        return 0;
    }
    const int sameBuild = layout == LayoutSignature();
    if (!sameBuild && !(portable && Port_Syms_Available())) {
        /* Its pointers into code and constants belong to another build's
         * layout and weren't all named; restoring it would crash. */
        fprintf(stderr, "[quicksave] %s was saved by a different build of the game%s — refusing load\n", path,
                portable ? " and tmc_pc.syms is missing" : "");
        fclose(f);
        return 0;
    }

    /* directory -> this build's regions */
    int map[1024];
    u32 dsize[1024];
    u64 dbase[1024];
    int ok = 1;
    for (u32 d = 0; ok && d < nregions; ++d) {
        u8 len = 0;
        char name[256];
        ok = fread(&len, 1, 1, f) == 1 && fread(name, 1, len, f) == len && fread(&dsize[d], 4, 1, f) == 1 &&
             fread(&dbase[d], 8, 1, f) == 1;
        name[ok ? len : 0] = 0;
        map[d] = -1;
        for (size_t i = 0; ok && i < NUM_REGIONS; ++i)
            if (strcmp(sRegions[i].name, name) == 0) {
                if (sRegions[i].size != dsize[d]) {
                    fprintf(stderr, "[quicksave] %s: %s changed size in this build (%u -> %zu) — refusing load\n",
                            path, name, dsize[d], sRegions[i].size);
                    fclose(f);
                    return 0;
                }
                map[d] = (int)i;
            }
    }
    u32 nrecs = 0;
    PtrRec* recs = NULL;
    ok = ok && fread(&nrecs, sizeof(nrecs), 1, f) == 1 && nrecs < (1u << 20);
    if (ok && nrecs)
        ok = (recs = (PtrRec*)calloc(nrecs, sizeof(PtrRec))) != NULL;
    u32 kept = 0;
    for (u32 k = 0; ok && k < nrecs; ++k) {
        PtrRec r;
        memset(&r, 0, sizeof(r));
        ok = fread(&r.region, sizeof(r.region), 1, f) == 1 && fread(&r.kind, 1, 1, f) == 1 &&
             fread(&r.keyLen, 1, 1, f) == 1 && fread(&r.at, sizeof(r.at), 1, f) == 1 &&
             fread(&r.offset, sizeof(r.offset), 1, f) == 1 && r.keyLen < sizeof(r.key) &&
             fread(r.key, 1, r.keyLen, f) == r.keyLen && r.region < nregions;
        if (ok && map[r.region] >= 0) {
            r.region = (u16)map[r.region];
            recs[kept++] = r;
        }
    }
    if (!ok) {
        fprintf(stderr, "[quicksave] short read on %s, ignoring slot file\n", path);
        free(recs);
        fclose(f);
        return 0;
    }

    /* data, laid out in this build's order; regions the file lacks keep
     * their current contents */
    Slot* s = &sSlots[slot];
    const size_t mine = TotalRegionBytes();
    if (s->snapshot == NULL || s->bytes != mine) {
        free(s->snapshot);
        s->snapshot = (u8*)malloc(mine);
        if (!s->snapshot) {
            s->bytes = 0, s->valid = 0;
            free(recs);
            fclose(f);
            return 0;
        }
        s->bytes = mine;
    }
    size_t at[1024];
    for (size_t i = 0, o = 0; i < NUM_REGIONS; o += sRegions[i].size, ++i) {
        at[i] = o;
        memcpy(s->snapshot + o, sRegions[i].ptr, sRegions[i].size);
        s->saved_bases[i] = (u64)(uintptr_t)sRegions[i].ptr; /* no relocation unless the file has it */
    }
    for (u32 d = 0; ok && d < nregions; ++d) {
        if (map[d] < 0) {
            ok = fseek(f, (long)dsize[d], SEEK_CUR) == 0;
            continue;
        }
        ok = fread(s->snapshot + at[map[d]], 1, dsize[d], f) == dsize[d];
        s->saved_bases[map[d]] = dbase[d];
    }
    fclose(f);
    if (!ok) {
        fprintf(stderr, "[quicksave] short read on %s data, ignoring slot file\n", path);
        free(recs);
        s->valid = 0;
        return 0;
    }
    free(s->recs);
    s->recs = recs, s->nrecs = kept;
    s->portable = (int)portable;
    s->valid = 1;
    s->saved_at_unix = saved_at;
    s->image_lo = image_lo, s->image_hi = image_hi;
    if (!sameBuild)
        fprintf(stderr, "[quicksave] %s is from another build; loading by region and symbol names\n", path);
    return 1;
}

/* ============================================================
 *   Public API
 * ============================================================ */

int Port_QuickSave_SaveSlot(int slot) {
    if (slot < 0 || slot >= NUM_SLOTS)
        return 0;
    if (!Snapshot_Capture(&sSlots[slot]))
        return 0;
    /* Best-effort disk persistence — failure is non-fatal, the in-memory
     * snapshot still works for the session. */
    WriteSlotToDisk(slot);
    fprintf(stderr, "[quicksave] slot %d saved (%zu bytes)\n", slot, sSlots[slot].bytes);
    return 1;
}

int Port_QuickSave_LoadSlot(int slot) {
    /* Refuse any state restore under Console-Parity — covers the menu/imgui
     * load buttons too, not just the F-key hotkeys. */
    if (Port_Config_GetConsoleParity())
        return 0;
    if (slot < 0 || slot >= NUM_SLOTS)
        return 0;
    if (!sSlots[slot].valid) {
        /* Try loading from disk first — handles "fresh launch, never
         * saved this session but slot exists on disk from last run". */
        if (!ReadSlotFromDisk(slot)) {
            fprintf(stderr, "[quicksave] slot %d empty\n", slot);
            return 0;
        }
    }
    if (!Snapshot_Restore(&sSlots[slot])) {
        fprintf(stderr, "[quicksave] slot %d restore failed\n", slot);
        return 0;
    }
    fprintf(stderr, "[quicksave] slot %d restored\n", slot);
    {
        /* Tell the Reborn-parity layer a resume just happened so it
         * can swallow the next queued Ezlo hint (if that toggle is on). */
        extern void Port_Reborn_NotifyJustResumed(void);
        Port_Reborn_NotifyJustResumed();
    }
    return 1;
}

int Port_QuickSave_HasSlot(int slot) {
    if (slot < 0 || slot >= NUM_SLOTS)
        return 0;
    if (sSlots[slot].valid)
        return 1;
    /* Probe disk so the menu can label populated-on-disk slots correctly
     * before the user touches them. */
    char path[64];
    SlotFilename(slot, path, sizeof(path));
    FILE* f = fopen(path, "rb");
    if (!f)
        return 0;
    fclose(f);
    return 1;
}

/* ---- Practice point -------------------------------------------------- *
 * A dedicated in-memory snapshot for the speedrun practice mode, kept
 * separate from the F1..F5 user slots so practising a segment never clobbers
 * a manual save. In-process only (no disk, no pointer fixup needed — the
 * entities base is unchanged within a run), so set/reload is a sub-ms memcpy.
 * Driven from port_practice.c via the Port_Practice_SetPoint/LoadPoint API. */
static Slot sPracticeSlot;

int Port_QuickSave_SavePractice(void) {
    if (!Snapshot_Capture(&sPracticeSlot))
        return 0;
    fprintf(stderr, "[quicksave] practice point set (%zu bytes)\n", sPracticeSlot.bytes);
    return 1;
}

int Port_QuickSave_LoadPractice(void) {
    if (Port_Config_GetConsoleParity())
        return 0;
    if (!sPracticeSlot.valid) {
        fprintf(stderr, "[quicksave] practice point empty\n");
        return 0;
    }
    if (!Snapshot_Restore(&sPracticeSlot)) {
        fprintf(stderr, "[quicksave] practice point restore failed\n");
        return 0;
    }
    {
        extern void Port_Reborn_NotifyJustResumed(void);
        Port_Reborn_NotifyJustResumed();
    }
    return 1;
}

int Port_QuickSave_HasPractice(void) {
    return sPracticeSlot.valid ? 1 : 0;
}

u64 Port_QuickSave_SlotTimestamp(int slot) {
    if (slot < 0 || slot >= NUM_SLOTS)
        return 0;
    if (sSlots[slot].valid)
        return sSlots[slot].saved_at_unix;
    /* Probe the disk file's timestamp header so the menu can show
     * "last saved" even for slots that haven't been loaded into memory. */
    char path[64];
    SlotFilename(slot, path, sizeof(path));
    FILE* f = fopen(path, "rb");
    if (!f)
        return 0;
    u32 magic = 0, version = 0, total = 0;
    u64 saved_at = 0;
    if (ReadSlotHeader(f, &magic, &version, &total, &saved_at)) {
        fclose(f);
        return saved_at;
    }
    fclose(f);
    return 0;
}

/* Legacy single-slot API — slot 0 is the F5/F6 quicksave. */
int Port_QuickSave(void) {
    return Port_QuickSave_SaveSlot(0);
}
int Port_QuickLoad(void) {
    return Port_QuickSave_LoadSlot(0);
}
int Port_QuickSave_HasSnapshot(void) {
    return Port_QuickSave_HasSlot(0);
}

/* Auto-save — call once per frame from VBlankIntrWait. Saves to the
 * next slot in the auto-save ring if enabled and the configured
 * interval has elapsed since the last auto-save. */
static void TakeAutoSnapshot(const char* reason) {
    const int slot = sAutoNextSlot;
    sAutoNextSlot++;
    if (sAutoNextSlot >= AUTO_SLOT_BASE + NUM_AUTO_SLOTS) {
        sAutoNextSlot = AUTO_SLOT_BASE;
    }
    if (Port_QuickSave_SaveSlot(slot)) {
        fprintf(stderr, "[autosave] saved to ring slot %d (%s)\n", slot, reason);
    }
}

void Port_QuickSave_AutoTick(void) {
    {
        /* ponytail: debug knob — TMC_REPRO_LOAD_SLOT=<n>: load state slot n
         * from the title screen, as the menu's resume does (crash repros). */
        static int titleFrames = 0, done = 0, after = 0;
        const char* ls = getenv("TMC_REPRO_LOAD_SLOT");
        if (ls && *ls && !done && gMain.task == TASK_TITLE && ++titleFrames > 2) {
            done = 1;
            fprintf(stderr, "[quicksave] repro: loading slot %d from title -> %d\n", atoi(ls),
                    Port_QuickSave_LoadSlot(atoi(ls)));
        }
        /* TMC_REPRO_LOAD_SHOT=<dir>: then capture <dir>/3d.png + 2d.png and
         * walk TMC_REPRO_LOAD_WALK (u/d/l/r) for 60 frames, logging where Link
         * ends up (did collision come back with the state?), and exit. */
        const char* shot = getenv("TMC_REPRO_LOAD_SHOT");
        if (done && shot && *shot) {
            ++after;
            if (after == 120) {
                char path[512];
                snprintf(path, sizeof(path), "%s/3d.png", shot);
                Port_Voxel_RequestShot(path);
                snprintf(path, sizeof(path), "%s/2d.png", shot);
                Port_CaptureBaseFramebufferPNG(path);
                fprintf(stderr, "[quicksave] repro: after load area=0x%02x room=0x%02x link=%d,%d\n",
                        gRoomControls.area, gRoomControls.room, gPlayerEntity.base.x.HALF.HI,
                        gPlayerEntity.base.y.HALF.HI);
            }
            const char* walk = getenv("TMC_REPRO_LOAD_WALK");
            if (walk && after > 130 && after < 190)
                Port_Config_TestForceEdge(*walk == 'u'   ? PORT_INPUT_UP
                                          : *walk == 'd' ? PORT_INPUT_DOWN
                                          : *walk == 'l' ? PORT_INPUT_LEFT
                                                         : PORT_INPUT_RIGHT);
            if (after == 200) {
                fprintf(stderr, "[quicksave] repro: after walk link=%d,%d\n", gPlayerEntity.base.x.HALF.HI,
                        gPlayerEntity.base.y.HALF.HI);
                fflush(stderr);
                _Exit(0);
            }
        }
    }
    if (QuickSaveReplayTestTick() || !sAutoEnabled)
        return;
    const u64 now = SDL_GetTicks();

    /* Area-change trigger. gRoomControls is the engine's source-of-
     * truth for the current area/room; we just compare against the
     * last value we observed and fire a snapshot on transition. The
     * first poll seeds the cache without saving (sLastSeen* both
     * 0xFF) so we don't double-save on boot. */
    if (sAutoOnAreaChange) {
        /* gRoomControls is declared in include/room.h, already in scope
         * via include/save.h above. */
        const u8 area = gRoomControls.area;
        const u8 room = gRoomControls.room;
        if (sLastSeenArea == 0xFF && sLastSeenRoom == 0xFF) {
            sLastSeenArea = area;
            sLastSeenRoom = room;
        } else if (area != sLastSeenArea || room != sLastSeenRoom) {
            sLastSeenArea = area;
            sLastSeenRoom = room;
            sAutoLastSaveTicksMs = now;
            TakeAutoSnapshot("area-change");
            return;
        }
    }

    /* Interval trigger. */
    if (sAutoLastSaveTicksMs == 0) {
        sAutoLastSaveTicksMs = now;
        return;
    }
    if (now - sAutoLastSaveTicksMs < sAutoIntervalMs)
        return;
    sAutoLastSaveTicksMs = now;
    TakeAutoSnapshot("interval");
}

int Port_QuickSave_AutoOnAreaChangeEnabled(void) {
    return sAutoOnAreaChange;
}
void Port_QuickSave_SetAutoOnAreaChange(int on) {
    sAutoOnAreaChange = on ? 1 : 0;
    /* Reset the seen-area cache when toggled on so the next change
     * doesn't fire spuriously against pre-toggle history. */
    if (on) {
        sLastSeenArea = 0xFF;
        sLastSeenRoom = 0xFF;
    }
}

void Port_QuickSave_SetAutoEnabled(int enabled) {
    sAutoEnabled = enabled ? 1 : 0;
    if (enabled)
        sAutoLastSaveTicksMs = SDL_GetTicks();
}

int Port_QuickSave_AutoEnabled(void) {
    return sAutoEnabled;
}

void Port_QuickSave_SetAutoIntervalMs(u32 ms) {
    if (ms < 5000)
        ms = 5000; /* clamp to 5s minimum — anything
                      faster would thrash on busy
                      frames and risk visible hitches. */
    if (ms > 600000)
        ms = 600000; /* 10 minute cap */
    sAutoIntervalMs = ms;
}

u32 Port_QuickSave_AutoIntervalMs(void) {
    return sAutoIntervalMs;
}

int Port_QuickSave_SlotCount(void) {
    return NUM_SLOTS;
}
int Port_QuickSave_AutoSlotBase(void) {
    return AUTO_SLOT_BASE;
}
int Port_QuickSave_AutoSlotCount(void) {
    return NUM_AUTO_SLOTS;
}
