#!/usr/bin/env python3
"""Generate port/port_quicksave_regions.h: every game RAM variable for save states.

linker.ld lists every variable the GBA game keeps in EWRAM/IWRAM. The PC port
defines most of them as ordinary globals, so a save state must capture each
one or a load leaves it as it was (the room's map and collision, the area,
running scripts, managers, HUD, message box...). This finds each name's
definition in src/ and port/ and emits

    QS_DECL(<declaration>)            an extern declaration with the full type
    QS_REGION(name, may_hold_pointers)
    QS_PRIVATE(name, may_hold_pointers)   type private to its .c file, which
                                          must say QS_EXPORT_SIZE(name)

Variables whose element type is a plain integer are marked as holding no
pointers, so the restore never relocates their contents. Audio engine state
(the PC port plays music on its own engine) and save-chip config are left out.

Run after adding or renaming a RAM global:
  python tools/gen_quicksave_regions.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "port" / "port_quicksave_regions.h"
SKIP = {
    # captured explicitly in port_quicksave.c
    "gSave", "gPlayerEntity", "gPlayerState", "gMain", "gRoomControls", "gRoomTransition", "gEntities",
    "gRand", "gEntityLists", "gAuxPlayerEntities", "gCarriedEntity", "gEntCount", "gManagerCount",
    "gActiveItems", "gEntityListsBackup", "gPlayerClones", "gUpdateContext",
    # live input: restoring it would replay held keys
    "gInput",
    # linker end marker
    "gEndOfEwram",
    # audio: the port's own engine, restored by the music manager, not GBA RAM state
    "gMPlayTracks", "gMPlayInfos", "gMPlayInfos2", "gSoundInfo", "gCgbChans", "gMPlayJumpTable",
    "SoundMainRAM_Buffer", "gSoundPlayingInfo", "gMPlayMemAccArea",
    # hardware / host config
    "gEEPROMConfig",
}
# Byte buffers the game carves structs (with pointers) out of.
POINTER_BUFFERS = {"gzHeap"}
INT_TYPES = {"u8", "u16", "u32", "u64", "s8", "s16", "s32", "s64", "bool8", "bool16", "bool32",
             "char", "int", "short", "long", "unsigned", "signed", "uint8_t", "uint16_t", "uint32_t"}


def ram_names() -> list[str]:
    ld = (ROOT / "linker.ld").read_text()
    names = []
    for sec in ("ewram", "iwram"):
        m = re.search(sec + r" \(NOLOAD\) : ALIGN\(4\) \{(.*?)\} >" + sec, ld, re.S)
        for n in re.findall(r"(\w+) = \.;", m.group(1)):
            if n not in names:
                names.append(n)
    return names


def definitions() -> dict[str, str]:
    """name -> definition text (type and declarator, no initializer/attributes)."""
    out = {}
    pat = re.compile(r"^(?!extern\b|static\b|typedef\b|return\b)([A-Za-z_][\w \*]*?)\b(\w+)\s*((?:\[[^\]]*\])*)"
                     r"\s*(?:__attribute__\(\(.*?\)\)\s*)?(?:=|;)", re.M)
    for f in list((ROOT / "src").rglob("*.c")) + list((ROOT / "port").rglob("*.c")):
        if "vk_rt_experiment" in f.parts:
            continue
        text = f.read_text(encoding="utf-8", errors="replace")
        for m in pat.finditer(text):
            typ, name, dims = m.group(1).strip(), m.group(2), m.group(3)
            if name in out or not typ or typ in ("else", "case"):
                continue
            out[name] = f"{typ} {name}{dims}"
    return out


def private_types() -> set[str]:
    """Struct types defined inside a .c file, not a header: their globals are
    declared here as bytes, with the size exported by the defining file."""
    def read_all(files):
        return "\n".join(f.read_text(encoding="utf-8", errors="replace") for f in files)

    pub = read_all((ROOT / "include").rglob("*.h"))
    src = read_all((ROOT / "src").rglob("*.c"))
    return {t for t in re.findall(r"\}\s*(\w+);", src)
            if not re.search(r"\}\s*" + t + r";|typedef [^;]*\b" + t + r";", pub)}


def main() -> int:
    defs = definitions()
    private = private_types()
    lines = ["/* Generated by tools/gen_quicksave_regions.py from linker.ld; do not edit.",
             " * Every game RAM variable the port defines as a host global, for save",
             " * states. QS_REGION(name, may_hold_pointers). */"]
    count = 0
    for n in ram_names():
        if n in SKIP or n.startswith("ram_") or n not in defs:  # ram_*: GBA code copied to RAM
            continue
        decl = defs[n]
        base = decl.split()[0]
        ptr = 0 if (base in INT_TYPES and "*" not in decl) else 1
        if n in POINTER_BUFFERS:
            ptr = 1
        if base in private:
            # size from QS_EXPORT_SIZE(name) in the file that defines the type
            lines.append(f"QS_DECL(extern unsigned char {n}[]; extern const unsigned gQsSize_{n};)")
            lines.append(f"QS_PRIVATE({n}, {ptr})")
        else:
            lines.append(f"QS_DECL(extern {decl};)")
            lines.append(f"QS_REGION({n}, {ptr})")
        count += 1
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{count} regions -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
